---
title: "Project Notebook"
author: "Minghao Du"
output:
  prettydoc::html_pretty:
    highlight: github
    toc: yes
    toc_depth: 2
    theme: architect
  '# prettydoc::html_pretty': default
---

```{css echo=FALSE}
@import url('https://fonts.googleapis.com/css2?family=Fira+Code:wght@300;400;500;600;700&display=swap');
code{
  font-family: 'Fira Code'!important;
}
```
```{r echo=FALSE}
library(rmarkdown)
if (!require(kableExtra)) install.packages("kableExtra")
library(kableExtra)
library(knitr)
library(magrittr)
```

# Intro

# Set-up
Load packages. 
```{r}
rm(list = ls())
if (!require(readxl)) install.packages("readxl")
library(readxl)
if (!require(tidyverse)) install.packages("tidyverse")
library(tidyverse)
if (!require(ggplot2)) install.packages("ggplot2")
library(ggplot2)

if (!require(e1071)) install.packages("e1071")
library(e1071)
if (!require(fastDummies)) install.packages("fastDummies")
library(fastDummies)

```

# Import Data

```{R}
raw_data <-
  read.csv(
    "../data/WA_Fn-UseC_-HR-Employee-Attrition.csv",
    stringsAsFactors = T,
    na.strings = '?'
  )

names(raw_data)[names(raw_data) == 'ï..Age'] <- 'Age'


glimpse(raw_data)
```

# Preprocess the data 

```{R}
data_droped_unusable_cols <-
  subset(
    raw_data,
    select = -c(
      Attrition,
      EmployeeNumber,
      EnvironmentSatisfaction,
      JobInvolvement,
      JobSatisfaction,
      OverTime,
      PercentSalaryHike,
      RelationshipSatisfaction,
      StockOptionLevel,
      TrainingTimesLastYear,
      WorkLifeBalance,
      YearsAtCompany,
      YearsInCurrentRole,
      YearsSinceLastPromotion,
      YearsWithCurrManager, 
      Over18, 
      EmployeeCount, 
      StandardHours
    )
  )

glimpse(data_droped_unusable_cols)
```
```{R}
data_dummied <- dummy_cols(data_droped_unusable_cols)

data_processed <-
  data_dummied[, sapply(data_dummied, class) != "factor"]

colnames(data_processed) <- gsub(" ", "", colnames(data_processed))
colnames(data_processed) <- gsub("-", "", colnames(data_processed))
colnames(data_processed) <- gsub("&", "", colnames(data_processed))
colnames(data_processed) <- gsub("`", "", colnames(data_processed))

data_processed$PerformanceRating <-
  as.factor(data_processed$PerformanceRating)

glimpse(data_processed)
```

```{R}
processedRating <-
  as.numeric(as.character(data_processed$PerformanceRating))

hist(processedRating)

rating_3_index <- which(processedRating %in% 3)

mutateable <-
  rating_3_index[sample(length(rating_3_index), size = length(rating_3_index) /
                          3 * 2)]

select <- sample(length(mutateable), size = length(mutateable) / 3 * 2)

mutate_2_select <- mutateable[select]

mutate_1_select <- mutateable[-select]

for (x in mutate_2_select) processedRating[x] = 2
for (x in mutate_1_select) processedRating[x] = 1

hist(processedRating)

data_processed$PerformanceRating <-
  as.factor(processedRating)
```


```{R}
svm_1 <-
  svm(
    PerformanceRating ~ .,
    data = data_processed,
    method = "C-classification",
    kernal = "radial",
    gamma = 0.1,
    cost = 10
  )

summary(svm_1)
plot(svm_1, data_processed)
```

